# Generated by Django 2.1.4 on 2018-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretSanta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret_santa_of',
            field=models.CharField(max_length=128, null='True'),
            preserve_default='True',
        ),
    ]
